name: CI/CD Pipeline

# Trigger actions on push and pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that will run in this workflow
jobs:
  # Job to test the Python application
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for the runner
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Change this to your Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # Step 4: Run tests (assuming you have pytest or another testing framework)
      - name: Run tests
        run: pytest  # Replace with the command for your testing tool (e.g., pytest)

  # Optionally, a deploy job (if you want to deploy to cloud platforms)
  deploy:
    runs-on: ubuntu-latest
    
    needs: test  # Ensure this job runs after the "test" job
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Example: If you are deploying to AWS, add commands here
      - name: Deploy to AWS
        run: |
          echo "Deploying to AWS..."
          # Add your cloud deployment script here (e.g., AWS CLI commands)
